### ISSUE TITLE
[Bug] [scaleph-api] Docker Java Runtime Version Error

### ISSUE THREAD

**Issue by SinyoWong** [flowerfine/scaleph#329]
### Already searched before asking?

- [X] I had searched in the [issues](https://github.com/flowerfine/scaleph/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Scaleph Version or Branch

latest

### What happened

用docker-compose up命令启动，报错：container for service "scaleph-api" is unhealthy
后面在本地尝试更改过JDK8、JDK11等多个版本，仍然报错。

### Error Exception

```log
Exception in thread "main" java.lang.UnsupportedClassVersionError: cn/sliew/scaleph/Application has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:46)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
```

### Are you willing to submit PR?

- [x] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/)

**Comment by SinyoWong** [comment]
![error](https://user-images.githubusercontent.com/38577585/195106127-c6924c07-f190-41a2-b95a-594494bfb375.jpg)

**Comment by SinyoWong** [comment]
![Uploading error2.jpg…]()

**Comment by SinyoWong** [comment]
![error2](https://user-images.githubusercontent.com/38577585/195220564-d06147ac-b8ba-4f51-ad5b-2e34fb022286.jpg)

**Comment by qianleijava** [comment]
我也遇到一样的问题

**Comment by SinyoWong** [comment]
> 我也遇到一样的问题

v 0.0.1 可以

**Comment by SinyoWong** [comment]
v 0.0.1 可以
