### ISSUE TITLE
What args should be input when Starting scaleph in IDEA 

### ISSUE THREAD

**Issue by Sigal0** [flowerfine/scaleph#576]
### Already searched before asking?

- [x] I had searched in the [issues](https://github.com/flowerfine/scaleph/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Scaleph Version or Branch

scaleph version: dev

### What happened

When I start Scaleph in IDEA, some error occurs like below, and it started failed.

### Error Exception

```log
2023-07-18 09:08:56.273  WARN 29972 [main] o.a.hadoop.metrics2.impl.MetricsConfig   136  行: Cannot locate configuration: tried hadoop-metrics2-s3a-file-system.properties,hadoop-metrics2.properties
2023-07-18 09:08:56.289  INFO 29972 [main] o.a.h.metrics2.impl.MetricsSystemImpl    378  行: Scheduled Metric snapshot period at 10 second(s).
2023-07-18 09:08:56.289  INFO 29972 [main] o.a.h.metrics2.impl.MetricsSystemImpl    191  行: s3a-file-system metrics system started
log4j:WARN No appenders could be found for logger (com.amazonaws.AmazonWebServiceClient).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
2023-07-18 09:08:57.511  INFO 29972 [main] cn.sliew.scaleph.Application             61   行: Started Application in 3.665 seconds (JVM running for 4.595)
2023-07-18 09:08:57.526  INFO 29972 [main] c.s.s.f.f.executor.FetcherExecutor       46   行: 命令行参数: []
2023-07-18 09:08:57.542 ERROR 29972 [main] c.s.s.f.f.executor.FetcherExecutor       52   行: 下载文件异常! 参数: []

cn.sliew.scaleph.file.fetcher.cli.CliArgsException: Missing required options: uri, path
	at cn.sliew.scaleph.file.fetcher.cli.OptionsParser.parse(OptionsParser.java:104)
	at cn.sliew.scaleph.file.fetcher.executor.FetcherExecutor.run(FetcherExecutor.java:47)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:762)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:752)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
	at cn.sliew.scaleph.Application.main(Application.java:28)
```

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/)

**Comment by kalencaya** [comment]
https://flowerfine.github.io/scaleph-website/zh/docs/contribute/develop

**Comment by Sigal0** [comment]
> 

I have followed the instructions ,but still failed with the same errors. I found there are two same class "cn.sliew.scaleph.Application",  one in scaleph-api, another in scaleph-file-fetcher

**Comment by Sigal0** [comment]
> https://flowerfine.github.io/scaleph-website/zh/docs/contribute/develop


I have followed the instructions ,but still failed with the same errors. I found there are two same class "cn.sliew.scaleph.Application", one in scaleph-api, another in scaleph-file-fetcher

**Comment by kalencaya** [comment]
![image](https://github.com/flowerfine/scaleph/assets/24804318/96216b01-b67c-42ba-a0ea-52652b7b7e6b)


bootstrap `cn.sliew.scaleph.Application` on `scaleph-api` module
