### ISSUE TITLE
[Bug][scaleph-engine-seatunnel] java.lang.UnsupportedOperationException: null 

### ISSUE THREAD

**Issue by gleiyu** [flowerfine/scaleph#68]
https://github.com/flowerfine/scaleph/blob/d2880b1ca00a2560c1dbc37b3db728517c5dadd3/scaleph-engine/scaleph-engine-seatunnel/src/main/java/cn/sliew/scaleph/engine/seatunnel/service/impl/SeatunnelJobServiceImpl.java#L312

Arrays.asList return type is a ArrayList which is an inner class in Arrays and is not java.util.ArrayList . this will cause exception when add element into list .

see https://wenku.baidu.com/view/e44fda2ea5c30c22590102020740be1e650eccd3.html

**Comment by gleiyu** [comment]
@kalencaya 
`
java.lang.UnsupportedOperationException: null
	at java.util.AbstractList.add(AbstractList.java:148)
	at java.util.AbstractList.add(AbstractList.java:108)
	at cn.sliew.scaleph.engine.seatunnel.service.impl.SeatunnelJobServiceImpl.lambda$buildJob$2(SeatunnelJobServiceImpl.java:317)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at cn.sliew.scaleph.engine.seatunnel.service.impl.SeatunnelJobServiceImpl.buildJob(SeatunnelJobServiceImpl.java:316)
	at cn.sliew.scaleph.engine.seatunnel.service.impl.SeatunnelJobServiceImpl.submit(SeatunnelJobServiceImpl.java:147)
	at cn.sliew.scaleph.engine.seatunnel.service.impl.SeatunnelFlinkJob.executeInternal(SeatunnelFlinkJob.java:43)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
`
