### ISSUE TITLE
[Bug] [scaleph-storage] java.io.FileNotFoundException: HADOOP_HOME and hadoop.home.dir are unset

### ISSUE THREAD

**Issue by gleiyu** [flowerfine/scaleph#85]
### Already searched before asking?

- [X] I had searched in the [issues](https://github.com/flowerfine/scaleph/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Scaleph Version or Branch

dev

### What happened

FileNotFoundException throws when startup

### Error Exception

```log
java.io.FileNotFoundException: java.io.FileNotFoundException: HADOOP_HOME and hadoop.home.dir are unset. -see https://wiki.apache.org/hadoop/WindowsProblems
	at org.apache.hadoop.util.Shell.fileNotFoundException(Shell.java:549)
	at org.apache.hadoop.util.Shell.getHadoopHomeDir(Shell.java:570)
	at org.apache.hadoop.util.Shell.getQualifiedBin(Shell.java:593)
	at org.apache.hadoop.util.Shell.<clinit>(Shell.java:690)
	at org.apache.hadoop.util.StringUtils.<clinit>(StringUtils.java:78)
	at org.apache.hadoop.conf.Configuration.getStringCollection(Configuration.java:2170)
	at org.apache.hadoop.fs.s3a.S3AUtils.patchSecurityCredentialProviders(S3AUtils.java:1174)
	at org.apache.hadoop.fs.s3a.S3AFileSystem.initialize(S3AFileSystem.java:240)
	at org.apache.flink.fs.s3.common.AbstractS3FileSystemFactory.create(AbstractS3FileSystemFactory.java:123)
	at cn.sliew.scaleph.storage.configuration.FileSystemConfiguration.s3FileSystem(FileSystemConfiguration.java:59)
	at cn.sliew.scaleph.storage.configuration.FileSystemConfiguration$$EnhancerBySpringCGLIB$$61a05adb.CGLIB$s3FileSystem$1(<generated>)
	at cn.sliew.scaleph.storage.configuration.FileSystemConfiguration$$EnhancerBySpringCGLIB$$61a05adb$$FastClassBySpringCGLIB$$99e9f8a8.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
```

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kalencaya** [comment]
I can't reproduce it on macos operate system.
Try add `config.set(CoreOptions.FLINK_HADOOP_CONF_DIR, "");` on `cn.sliew.scaleph.storage.configuration.FileSystemConfiguration` as follows:
<img width="1223" alt="image" src="https://user-images.githubusercontent.com/24804318/174604673-22ea98fa-30ab-4dfb-98c8-958b2463005b.png">

**Comment by gleiyu** [comment]
@kalencaya  
see [WindowsProblems](https://cwiki.apache.org/confluence/display/HADOOP2/WindowsProblems)
1. clone git@github.com:steveloughran/winutils.git
2. set environment variable %HADOOP_HOME% to point to the directory above the BIN dir containing WINUTILS.EXE
